# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wDpejmbUyGu6larlVE_QzekChaK4MVIT
"""

import streamlit as st
import tensorflow as tf
from PIL import Image
import numpy as np
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
import io
import base64
# --- Label dan Khasiat ---
class_names = [
    'Ancak', 'AwarAwar', 'Beringin', 'Cemara', 'CempakaKuning',
    'Ceremai', 'Dapdap', 'Delima', 'Gadung', 'JambuAir',
    'JambuBiji', 'JarakPagar', 'JerukLimau', 'JerukSitrun', 'Juwet',
    'KacaPiring', 'Kamboja', 'Kasimbukan', 'Kecubung', 'Kelor',
    'Keluak', 'KembangSepatu', 'Kepundung', 'KetimunGantung', 'Kopi',
    'Lantana', 'Legundi', 'ManggaAmplem', 'Manggis', 'Mengkudu',
    'Merica', 'Nanas', 'PakisSayur', 'Pala', 'Pare',
    'Pepaya', 'Pule', 'Salam', 'Semanggi', 'Sembung',
    'Sirih', 'Sirsak', 'Sisih', 'Srikaya', 'Suren',
    'Talas', 'Teleng', 'TerongDuri', 'UyahUyah', 'Wani'
]

khasiat_daun = {
    'Ancak': 'Menurunkan demam dan membantu mengatasi gangguan pencernaan.',
    'AwarAwar': 'Mengobati luka, mengurangi peradangan, dan mengatasi infeksi kulit.',
    'Beringin': 'Membantu mengatasi diare, bersifat antiseptik, dan menurunkan demam.',
    'Cemara': 'Meredakan batuk, menghangatkan tubuh, dan bersifat antimikroba.',
    'CempakaKuning': 'Mengurangi peradangan, meredakan nyeri, dan menenangkan pikiran.',
    'Ceremai': 'Menurunkan kadar gula darah, sebagai antioksidan, dan meredakan batuk.',
    'Dapdap': 'Mengobati luka, mengurangi nyeri, dan menenangkan saraf.',
    'Delima': 'Kaya antioksidan, menjaga kesehatan jantung, dan menurunkan tekanan darah.',
    'Gadung': 'Mengurangi nyeri rematik dan peradangan setelah diolah dengan benar.',
    'JambuAir': 'Membantu mengontrol gula darah dan menjaga sistem pencernaan.',
    'JambuBiji': 'Mengatasi diare, bersifat antibakteri, dan menurunkan kolesterol.',
    'JarakPagar': 'Mengobati luka, bersifat antiinflamasi, dan antibakteri.',
    'JerukLimau': 'Meredakan batuk dan menyegarkan pernapasan.',
    'JerukSitrun': 'Meningkatkan daya tahan tubuh, antioksidan, dan membantu detoksifikasi.',
    'Juwet': 'Menurunkan gula darah dan membantu mengatasi diare.',
    'KacaPiring': 'Mengurangi peradangan, menenangkan tubuh, dan membantu mengatasi insomnia.',
    'Kamboja': 'Meredakan nyeri sendi dan bersifat antiinflamasi.',
    'Kasimbukan': 'Mengatasi sakit perut dan bersifat antimikroba.',
    'Kecubung': 'Digunakan sebagai pereda nyeri dan obat asma tradisional (penggunaan terbatas).',
    'Kelor': 'Meningkatkan imunitas, menurunkan gula darah, dan kaya antioksidan.',
    'Keluak': 'Membantu penyembuhan luka dan bersifat antibakteri.',
    'KembangSepatu': 'Menyuburkan rambut dan membantu meredakan batuk.',
    'Kepundung': 'Menurunkan demam dan melancarkan pencernaan.',
    'KetimunGantung': 'Menurunkan tekanan darah dan membantu detoksifikasi tubuh.',
    'Kopi': 'Mengandung antioksidan dan membantu meningkatkan metabolisme.',
    'Lantana': 'Bersifat antiseptik dan membantu mengobati luka.',
    'Legundi': 'Meredakan batuk dan mengurangi peradangan.',
    'ManggaAmplem': 'Sebagai antioksidan dan membantu menjaga pencernaan.',
    'Manggis': 'Mengandung antioksidan tinggi dan bersifat antikanker.',
    'Mengkudu': 'Menurunkan tekanan darah dan meningkatkan daya tahan tubuh.',
    'Merica': 'Melancarkan pencernaan dan bersifat antibakteri.',
    'Nanas': 'Mengurangi peradangan dan membantu pencernaan.',
    'PakisSayur': 'Menyehatkan sistem pencernaan dan kaya antioksidan.',
    'Pala': 'Menenangkan saraf dan membantu mengatasi insomnia.',
    'Pare': 'Menurunkan kadar gula darah dan membantu pengobatan diabetes.',
    'Pepaya': 'Melancarkan pencernaan dan membantu meningkatkan trombosit.',
    'Pule': 'Menurunkan demam dan digunakan sebagai obat antimalaria tradisional.',
    'Salam': 'Menurunkan kolesterol dan membantu mengontrol gula darah.',
    'Semanggi': 'Melancarkan peredaran darah dan meningkatkan stamina.',
    'Sembung': 'Mengatasi masuk angin dan bersifat antiinflamasi.',
    'Sirih': 'Sebagai antiseptik alami dan menjaga kesehatan mulut.',
    'Sirsak': 'Dipercaya memiliki sifat antikanker dan antibakteri.',
    'Sisih': 'Digunakan sebagai obat luka tradisional.',
    'Srikaya': 'Mengatasi peradangan dan digunakan untuk menghilangkan kutu.',
    'Suren': 'Bersifat antimikroba dan membantu mengatasi infeksi kulit.',
    'Talas': 'Menjaga kesehatan pencernaan dan sebagai sumber antioksidan.',
    'Teleng': 'Kaya antioksidan dan menyehatkan mata.',
    'TerongDuri': 'Meredakan nyeri dan peradangan.',
    'UyahUyah': 'Menurunkan tekanan darah dan membantu melancarkan ASI.',
    'Wani': 'Sebagai antioksidan dan meningkatkan daya tahan tubuh.'
}

# --- Load Model ---
@st.cache_resource
def load_model():
    return tf.keras.models.load_model('mobilenetv2_model.h5')

# --- Preprocessing ---
def preprocess_and_predict(model, image):
    image = image.convert('RGB').resize((224, 224))
    image_array = preprocess_input(np.expand_dims(np.array(image), axis=0))
    prediction = model.predict(image_array)
    idx = np.argmax(prediction)
    return class_names[idx], np.max(prediction) * 100

# --- UI Layout ---
st.set_page_config(page_title="Klasifikasi Daun Herbal", layout="centered")
st.markdown("<h3 style='text-align: center;'><span style='color:#0abf53;'>CARI</span> TANAMAN HERBAL<br><span style='color:#1abc9c;'>DENGAN</span> SATU KLIK!!</h3>", unsafe_allow_html=True)
st.markdown("---")

# --- Pilihan Input ---
st.markdown("### Pilih metode input dari tombol di bawah 👇")
st.markdown("---")

# Buat state session
if "input_mode" not in st.session_state:
    st.session_state.input_mode = None

# Tombol Pilihan Input
col1, col2, col3, col4, col5 = st.columns(5)
with col2:
    if st.button("📷", help="Gunakan Kamera"):
        st.session_state.input_mode = "camera"
with col4:
    if st.button("🖼️", help="Upload Gambar"):
        st.session_state.input_mode = "upload"

# --- Load Model ---
model = load_model()
image = None

# --- Input Gambar ---
if st.session_state.input_mode == "upload":
    uploaded_file = st.file_uploader("Upload gambar daun", type=["jpg", "jpeg", "png"])
    if uploaded_file:
        image = Image.open(uploaded_file)

elif st.session_state.input_mode == "camera":
    camera_image = st.camera_input("Ambil gambar dari kamera")
    if camera_image:
        image = Image.open(camera_image)

# --- Output dan Hasil ---
if image:
    # Resize proporsional maksimal 300x300 px
    resized_image = image.copy()
    resized_image.thumbnail((224, 224))

    # Konversi ke base64 untuk disisipkan ke HTML agar center 100%
    buffered = io.BytesIO()
    resized_image.save(buffered, format="PNG")
    img_b64 = base64.b64encode(buffered.getvalue()).decode()

    # Tampilkan gambar center dengan HTML
    st.markdown(
        f"""
        <div style="text-align:center;">
            <img src="data:image/png;base64,{img_b64}" alt="Gambar Daun" style="max-height:300px; border-radius:10px;" />
            <p style="color:gray;">Gambar Daun</p>
        </div>
        """,
        unsafe_allow_html=True
    )

    with st.spinner("Menganalisis gambar..."):
        predicted_class, confidence = preprocess_and_predict(model, image)
        manfaat = khasiat_daun.get(predicted_class, "Khasiat tidak ditemukan.")

    st.markdown("---")
    st.markdown(f"<p style='text-align:center; font-size:24px; color:#0abf53;'><strong>{predicted_class}</strong></p>", unsafe_allow_html=True)
    st.markdown(f"<p style='text-align:center; font-size:16px;'>Tingkat Keyakinan: <strong>{confidence:.2f}%</strong></p>", unsafe_allow_html=True)
    st.markdown(f"<p style='text-align:center; font-size:18px; color:#ccc; border-left: 4px solid #0abf53; padding-left: 10px;'><strong>Khasiat:</strong> {manfaat}</p>", unsafe_allow_html=True)

else:
    st.info("Pilih metode input dari tombol di bawah (kamera atau upload gambar).")