# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fgR8NR0AC-V193vluQZxhPTM8wYgqI2Q
"""

import streamlit as st
import tensorflow as tf
import numpy as np
import json
from PIL import Image

# ==============================
# CONFIG
# ==============================
st.set_page_config(
    page_title="Klasifikasi Daun Herbal",
    layout="centered"
)

IMG_SIZE = (224, 224)
CONF_THRESHOLD = 60  # %

# ==============================
# LOAD MODEL & CLASS
# ==============================
@st.cache_resource
def load_model_and_class():
    model = tf.keras.models.load_model("mobilenetv2_daun_herbal.h5")

    with open("class_indices.json") as f:
        class_indices = json.load(f)

    class_names = list(class_indices.keys())
    return model, class_names

model, class_names = load_model_and_class()

# ==============================
# DATA KHASIAT (BISA DITAMBAH)
# ==============================
khasiat_dict = {
    "Belimbing Wuluh": "Menurunkan tekanan darah dan membantu batuk",
    "Jambu Biji": "Mengatasi diare dan meningkatkan daya tahan tubuh",
    "Jeruk Nipis": "Meredakan batuk dan meningkatkan imun",
    "Kemangi": "Mengurangi bau badan dan melancarkan pencernaan",
    "Lidah Buaya": "Menyehatkan kulit dan rambut",
    "Nangka": "Melancarkan pencernaan dan sumber energi",
    "Pandan": "Menurunkan tekanan darah dan memberi aroma alami",
    "Pepaya": "Melancarkan pencernaan",
    "Seledri": "Menurunkan kolesterol dan tekanan darah",
    "Sirih": "Antiseptik alami dan kesehatan mulut"
}

# ==============================
# PREDICT FUNCTION
# ==============================
def predict_image(img):
    img = img.convert("RGB").resize(IMG_SIZE)
    img_array = np.array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    preds = model.predict(img_array)[0]
    idx = np.argmax(preds)
    confidence = preds[idx] * 100

    return class_names[idx], confidence

# ==============================
# UI
# ==============================
st.title("🌿 Klasifikasi Daun Herbal")
st.write("Upload gambar daun untuk mengetahui jenis dan khasiatnya")

uploaded_file = st.file_uploader(
    "Upload gambar daun",
    type=["jpg", "jpeg", "png"]
)

if uploaded_file:
    image = Image.open(uploaded_file)
    st.image(image, caption="Gambar Daun", use_column_width=True)

    with st.spinner("Menganalisis gambar..."):
        label, confidence = predict_image(image)

    st.subheader("📌 Hasil Prediksi")

    if confidence < CONF_THRESHOLD:
        st.warning("⚠️ Model belum yakin dengan gambar ini")
    else:
        st.success(f"🌱 Jenis Daun : **{label}**")
        st.write(f"🎯 Confidence : **{confidence:.2f}%**")

        khasiat = khasiat_dict.get(label, "Khasiat belum tersedia")
        st.info(f"💊 Khasiat : {khasiat}")